### ISSUE TITLE
Simulate Protected API responses

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#116]
Microsoft Teams APIs in Microsoft Graph that access sensitive data are considered protected APIs. These APIs require that you have additional validation beyond permissions and consent before you can use them. Access to these APIs require a request to be completed and approved.

The proxy should provide mock data for these APIs to make it easier to developers to build applications that use these APIs.

https://learn.microsoft.com/en-us/graph/teams-protected-apis

**Comment by waldekmastykarz** [comment]
Just to clarify: you mean that we should provide mock data for these APIs together with the proxy, right? Because, just mocking them should be possible already today. Correct?

**Comment by garrytrinder** [comment]
Good catch, @waldekmastykarz, yes, that's what I meant. I've updated the OP.

**Comment by waldekmastykarz** [comment]
Closing this as we're not planning to work on this for the moment
