### ISSUE TITLE
[How-to guide]: Configure proxy to watch your own API

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#129]
In v0.3 release we introduced the ability to use the proxy with any API, we need to provide a guide to explain how you can inspect traffic from your own custom API.

**Comment by garrytrinder** [comment]
This can be closed, we provide this as part of the getting started tutorial.

https://github.com/microsoftgraph/msgraph-developer-proxy/wiki/Using-the-proxy-for-the-first-time#4-intercept-requests-to-any-api

**Comment by waldekmastykarz** [comment]
Done recently
