### ISSUE TITLE
Chaos test Azure Functions connected to Graph

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#14]
Document the steps to chaos test Azure Functions that use Graph:

- deploy chaos proxy so that it's accessible by Azure Functions
- update Azure Functions code to use the proxy when calling Graph

**Comment by phillipharding** [comment]
Is there any update on this, it would be super super super useful to test functions app like this during local dev 🤓

**Comment by waldekmastykarz** [comment]
We haven't planned it for February. That said, we appreciate you bringing it up. Let's see if we can shuffle things around to address this earlier. Thank you ❤️

**Comment by waldekmastykarz** [comment]
@phillipharding out of curiosity, do you build Azure Functions using VSCode or VS? Which language do you use, c# or JS?

**Comment by phillipharding** [comment]
@waldekmastykarz I use VSCode and NodeJS style functions apps, developed using TypeScript bundled to JavaScript

**Comment by waldekmastykarz** [comment]
Cool! I'll take that as the starting point to check out the current experience. In your functions, do you typically call Graph or other APIs as well? Do you use any specific HTTP client/SDK or fetch?

**Comment by phillipharding** [comment]
Typically Graph and the SharePoint APIs using either PnPJs or native fetch

**Comment by waldekmastykarz** [comment]
And which version of Node are you using for runtime? The reason I'm asking, is that fetch in Node.js is experimental and older versions don't support proxying requests.

**Comment by phillipharding** [comment]
Sorry, not native fetch but the node-fetch package with node v16

**Comment by waldekmastykarz** [comment]
Gotcha. Thank you for all the information @phillipharding, it'll help us scope the research. I hope we'll have more to share shortly 😊

**Comment by waldekmastykarz** [comment]
@phillipharding, would this be code similar to what you've got? Just checking if we're looking at the same thing 😊 

```ts
import { app, HttpRequest, HttpResponseInit, InvocationContext } from "@azure/functions";
import fetch from 'node-fetch';

export async function GraphHttpTrigger(request: HttpRequest, context: InvocationContext): Promise<HttpResponseInit> {
    // auth goes here
    const resp = await fetch('https://graph.microsoft.com/v1.0/users');
    const data = await resp.json();
    return {
        status: 200,
        jsonBody: data
    };
};

app.http('GraphHttpTrigger', {
    methods: ['GET', 'POST'],
    // unlikely in prod, but keeping it simple for now
    authLevel: 'anonymous',
    handler: GraphHttpTrigger
});

```

**Comment by waldekmastykarz** [comment]
Closing due to lack of response
