### ISSUE TITLE
Guidance for moving from Chaos Handler to Dev Proxy

### ISSUE THREAD

**Issue by sebastienlevert** [microsoft/dev-proxy#178]
We should write a guidance to help move folks from the Chaos Handler to the Dev Proxy. We should also have a documentation page that highlights the scenarios and when to use what. The proxy should identify when the chaos handler is used and offer guidance on how to use the Dev Proxy to achieve similar handling.

**Comment by waldekmastykarz** [comment]
If the Chaos Handler intercepts requests and prevents them from going out, won't it make it impossible for us to detect them in the proxy?

**Comment by sebastienlevert** [comment]
It's the same approach where it's based on a failure rate. We will be getting them and we can identify that the Chaos Handler was used via the features bitmask : https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/RequestContext.md

**Comment by waldekmastykarz** [comment]
Got it! If there's something we could watch out for, we could totally do this. 👍
