### ISSUE TITLE
Identify monetized APIs

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#214]

**Comment by sebastienlevert** [comment]
The only available documentation we have is this : https://learn.microsoft.com/en-us/graph/metered-api-list?view=graph-rest-1.0

We will be using this list as our foundation. Should we try automating getting the appropriate endpoints or should we build a static json file in our repo and get notifications when this file is updated? 

Thoughts @waldekmastykarz

**Comment by waldekmastykarz** [comment]
Since it's just a handful of endpoints that won't be changing without upfront notice, I suggest that for now we keep the list static and look into automating building it when it becomes necessary.

**Comment by sebastienlevert** [comment]
I'll build a spec based on that! Thanks for the feedback!
