### ISSUE TITLE
[How-to guide]: modify config to add custom plugin

### ISSUE THREAD

**Issue by Adam-it** [microsoft/dev-proxy#225]
Hi folks 👋,

So I noticed that currently there is little guidance around developing and adding (or replacing existing ones with) custom plugins. 
I mean the `appsettings.json` seems quite clear but I think some additional guidance would make it crystal clear. 
Also do you plan to extend `mgd` with maybe some functionality, like a command, which will allow to install (setup) a custom plugin?

Thank you for your awesome work 👍

**Comment by waldekmastykarz** [comment]
Good catch and definitely something we need to improve. Thank you for bringing it up @Adam-it!
