### ISSUE TITLE
[BUG]: Configuration settings do not get automatically reloaded when proxy is running

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#247]
## Description

When making changes to the `appsettings.json` file or loaded configuration file whilst the proxy is running, the changes do not take effect until the proxy is stopped and restarted.

## Expected behaviour

Proxy reloads the configuration automatically on save.

## Actual behaviour

Changes are not loaded automatically.

## Steps to reproduce

1. Start proxy, with or without specific configuration file
2. Make a change to the configuration file e.g. change failure rate to 100 or 0,

## Environment

OS: Windows 11
Shell: PowerShell
MGDP: 0.6.0

**Comment by waldekmastykarz** [comment]
I can repro the issue on macOS too.

**Comment by garrytrinder** [comment]
Whilst investigating this issue, it appears to be down to the way that the `reloadOnChange` option is implemented. It's not as simple as setting the flag and everything reloads when the `appsettings` change.

> The problem lies in the fact that although the IConfigurationRoot is automatically updated whenever the underlying appsettings.json file changes, the strongly typed configuration IOptions<> is not. Instead, the IOptions<> is created as a singleton when first requested and is never updated again. [Reloading strongly typed options in ASP.NET Core 1.1.0](https://andrewlock.net/reloading-strongly-typed-options-in-asp-net-core-1-1-0/)

In our case the configuration is only loaded once when the proxy is started. After that, the proxy engine takes over and monitors the requests coming in, or detecting key presses, such as start/stop recording or exit.

One approach we could take is for us to manually watch the file and reload its configuration when it changes, in a similar way to how we handle changes to the `responses` and `errors` files.

@gavinbarron would be great to hear your thoughts/ideas on how we fix this.

**Comment by nicodecleyre** [comment]
Hi,

Don't know if it can help but maybe you could make use of the reload token here?
If you register a changeTokenConsumer action:
```c#
        ChangeToken.OnChange(() => configuration.GetReloadToken(), () =>
        {
            Console.WriteLine("Hello msgraph-developer-proxy, config is changed");
        });
```

Here right after the bind action:
https://github.com/microsoftgraph/msgraph-developer-proxy/blob/b0c5412164e3482b2667169c98003d9cf1280a9e/msgraph-developer-proxy/ProxyCommandHandler.cs#L111-L120


So it looks like this:
```c#
    private static readonly Lazy<ProxyConfiguration> ConfigurationFactory = new(() => {
        var builder = new ConfigurationBuilder();
        var configuration = builder
                .AddJsonFile(ProxyHost.ConfigFile, optional: true, reloadOnChange: true)
                .Build();
        var configObject = new ProxyConfiguration();
        configuration.Bind(configObject);

        ChangeToken.OnChange(() => configuration.GetReloadToken(), () =>
        {
            Console.WriteLine("Hello msgraph-developer-proxy, config is changed");
        });

        return configObject;
    });
```

If you put a breakpoint in this OnChange event, you'll see that it gets hit whenever you change the `mgdprc.json` file is edited. From there you could opt to use this new config file

**Comment by waldekmastykarz** [comment]
This is a great suggestion @nicodecleyre! Thank you! We'll definitely check it out! ❤️

**Comment by garrytrinder** [comment]
Awesome suggestion @nicodecleyre 👏 Thank you!

**Comment by waldekmastykarz** [comment]
Hey @nicodecleyre, would you be willing to submit a PR for this? 😊

**Comment by nicodecleyre** [comment]
> Hey @nicodecleyre, would you be willing to submit a PR for this? 😊

Would love to! Thx for asking 😍

**Comment by waldekmastykarz** [comment]
Awesome! I appreciate you helping us

**Comment by waldekmastykarz** [comment]
Having looked at it again, I don't think we should support hot reloading. Proxy's settings can be very simple, such as failure rate, but can also change the port on which the proxy is running or even add plugins. To refresh this configuration on the fly we'd need to basically cleanup and rewrite the initialization code. It seems like an unnecessary complexity given the little overhead there's involved with manually restarting the proxy after changing its config. As such, I suggest we close this issue for now and revisit in the future should our stance change.
