### ISSUE TITLE
[Feature] - provide middleware that is compatible with Graph client

### ISSUE THREAD

**Issue by pschaeflein** [microsoft/dev-proxy#265]
I can build a graph client including middleware that I choose. Make the proxy logic (rules/reporting/etc) as a middleware.

https://learn.microsoft.com/en-us/graph/sdks/customize-client

**Comment by waldekmastykarz** [comment]
Interesting suggestion. We'll need to dig deeper into it to see how we could do that since the way we interecept requests now is different from the middleware and while the information we get to see is roughly similar, it's not exactly the same. Thanks for bringing it up!

**Comment by xzf0587** [comment]
I met the case too.
The proxy works fine with graph client in frontend code. But it does not work in backend call (the most common OBO scenario).

**Comment by waldekmastykarz** [comment]
@xzf0587 could you please tell us more about your setup? Since proxy sits on the HTTP stack it should work with any tech

**Comment by xzf0587** [comment]
Here is 3 case I tried,
`
import { HttpsProxyAgent } from "hpagent";
import * as https from 'https';

const agent = new HttpsProxyAgent({
    keepAlive: true,
    keepAliveMsecs: 1000,
    maxSockets: 256,
    maxFreeSockets: 256,
    proxy: 'http://127.0.0.1:8000',
    rejectUnauthorized: false,
  })
  
  https.get('https://graph.microsoft.com/v1.0/users/2', { agent}, (res) => {
    console.log('"response" event!', res.headers);
    res.pipe(process.stdout);
  });
`

**Comment by waldekmastykarz** [comment]
Thanks for the details. Which version of Node are you using?

**Comment by xzf0587** [comment]
> Thanks for the details. Which version of Node are you using?

node 18

**Comment by waldekmastykarz** [comment]
fetch in Node 18 is experimental and doesn't support proxies. You'd need to use another fetch client unfortunately.

**Comment by waldekmastykarz** [comment]
Given the difference in implementation it seems not feasible. We won't be working on this feature at the moment. Thanks for the suggestion.
