### ISSUE TITLE
Rename project and output executable due to extended functionality

### ISSUE THREAD

**Issue by kilasuit** [microsoft/dev-proxy#285]
### Description

As this can be used for other APIs as well as M365 api's perhaps changing this to API Dev Proxy many make more sense with the executable being called `apiproxy` if that is not already in use elsewhere from scans of package managers etc

This would be a breaking change with a rename to the executable but makes sense going forward

### Expected behaviour

N/a

### Actual behaviour

N/a

### Steps to reproduce

N/a

### Microsoft 365 Developer Proxy Version

N/a

### Operating system (environment)

Windows

### Shell

PowerShell

**Comment by waldekmastykarz** [comment]
Thanks for the suggestion @kilasuit 👍

**Comment by waldekmastykarz** [comment]
Closed with #382. The new name is Dev Proxy. Thanks again for bringing it up!
