### ISSUE TITLE
Build mocks from HAR files

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#308]
Extend proxy with support for creating mocks from HAR files.

HAR files are a standard way for storing information about web requests and responses. Users can create HAR files using different dev tools that range from Fiddle to Chrome dev tools. To simplify creating proxy mocks, we should consider extending proxy with support for creating mocks from HAR files.

Add a subcommand named `mocksfromhar` (you'd execute it by calling `m365proxy mocksfromhar`) to proxy that's capable of generating mocks from a HAR file. The command takes as an argument the path to the HAR file and the path to the output mock file.

IIRC there are several versions of the HAR format and we need to check which one is the most commonly used.

**Comment by waldekmastykarz** [comment]
@gavinbarron @sebastienlevert @garrytrinder any feedback?

**Comment by sebastienlevert** [comment]
Yes, but I would prefer this later where we should invest in recording mode and generating mocks via the Proxy directly. That way people could build their mocks and use them as part of the same tool.

Besides that, I think we should be more "generic" and probably leave area for other formats in the future, so something like:

`m365proxy buildmocks --type har`

That way we could bring a json file in the future, etc.

**Comment by mosoftwareenterprises** [comment]
This looks to be a duplicate of https://github.com/microsoft/m365-developer-proxy/issues/56

**Comment by mosoftwareenterprises** [comment]
The capability to put the proxy in a recording mode and generating a mocks files from that was the exact use case I was looking for from this tool.
I have a Compliance Recording app, and that functionality would significantly increase the use of this tool.

**Comment by sebastienlevert** [comment]
Do you need HAR support or JSON would be enough? In our latest release, we have shipped the mock generator plugin that can essentially do what you are looking for : https://github.com/microsoft/m365-developer-proxy/releases/tag/v0.12.0

Let us know if this makes sense!

**Comment by mosoftwareenterprises** [comment]
Thanks for the update. I will look into that plugin now.

No I dont need HAR support, the JSON is plenty thanks.

**Comment by waldekmastykarz** [comment]
We'll not be working on this feature at the moment.
