### ISSUE TITLE
Add support for combining rate limiting with mock responses

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#350]
Add support for combining rate limiting with mock responses. Right now, simulating rate limiting works only on requests that are passed through which still affects live API quota. Being able to use mock responses would allow developers to isolate testing and simulate rate limiting without affecting the actual API quota. The reason why this is not possible at the moment, because we send mock responses by intercepting requests and responding to them directly skipping the response pipeline, where we apply rate limiting information.

One way of solving this, would be to persist rate limiting information on the request before we apply mocks, and then, when we apply mocks, add rate limiting information if available.

**Comment by waldekmastykarz** [comment]
@microsoft/m365-developer-proxy-write thoughts?

**Comment by garrytrinder** [comment]
Makes sense to me, great idea.
