### ISSUE TITLE
[Docs] Add IP address option

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#389]
@garrytrinder we also should add to our docs, that on macOS, folks should configure proxy to listen on a specific port rather than 0.0.0.0, because it breaks updating the Graph DB and looking up minimal permissions.

_Originally posted by @waldekmastykarz in https://github.com/microsoft/dev-proxy/issues/388#issuecomment-1814645240_

**Comment by waldekmastykarz** [comment]
Since we changed the default port to 127.0.0.1 this is no longer needed, but we should double check we explain the configuration option
