### ISSUE TITLE
Mocking OPTIONS requests

### ISSUE THREAD

**Issue by martinlingstuyl** [microsoft/dev-proxy#411]
We're trying to mimic a CORS response using the devproxy. We're trying it as follows, using the OPTIONS method, but the devproxy just passes through the request. If we change it to POST or GET, the devproxy catches the request. Is this expected bahavior?

```json
{
  "responses": [
    {
      "url": "https://xxx-transferto.azurewebsites.net/api/*",
      "method": "OPTIONS",
      "responseBody":{},
      "responseCode": 200,
      "responseHeaders": {
        "Access-Control-Allow-Origin": "https://contoso.sharepoint.com/"
      }
    }
  ]
}
```

I did see a [closed issue](https://github.com/microsoft/dev-proxy/issues/16) about OPTIONS-requests, that suggests devproxy ignores it.

**Comment by martinlingstuyl** [comment]
Awesome, @waldekmastykarz, @garrytrinder!

**Comment by waldekmastykarz** [comment]
We're going to release a new preview version of Dev Proxy with this feature today. Looking forward to hearing how you like it. Please, don't hesitate to reach out if we can help further

**Comment by waldekmastykarz** [comment]
@martinlingstuyl, try https://github.com/microsoft/dev-proxy/releases/tag/v0.14.0-beta.1

**Comment by martinlingstuyl** [comment]
We'll try it out!

**Comment by martinlingstuyl** [comment]
Just tried it out with a mock response. Works like a glove! 🥳

**Comment by waldekmastykarz** [comment]
Awesome! Thanks again for working with us!
