### ISSUE TITLE
Structured logging?

### ISSUE THREAD

**Issue by svrooij** [microsoft/dev-proxy#412]
In the code of the dev proxy I see a lot of logging done in an unstructured way, which sets a bad example (in my opinion).

Things like:
https://github.com/microsoft/dev-proxy/blob/d2042e8d0ab351c1eef5bbdc8916e8e522323aae/dev-proxy/ProxyCommandHandler.cs#L86-L88

can also be written as, with exactly the same functionality:
```csharp
 _logger.LogError("New Dev Proxy version {versionNumber} is available.\r\nSee {upgradeUrl} for more information.\r\n", newReleaseInfo.Version, "https://aka.ms/devproxy/upgrade"); 
```

This will output the same error, while also showing logging best practices and allowing the extraction of the important details like the new version number and the url to upgrade.

The same can be set on:
https://github.com/microsoft/dev-proxy/blob/d2042e8d0ab351c1eef5bbdc8916e8e522323aae/dev-proxy/ProxyCommandHandler.cs#L95-L106

```csharp
  catch (Exception ex) {
      _logger.LogError(ex, "An error occurred while running Dev Proxy {message}", ex.Message.ToString());
      var inner = ex.InnerException;

      while (inner is not null) {
          _logger.LogError(inner, "============ Inner exception ============\r\n{message}", inner.Message.ToString());
          inner = inner.InnerException;
      }
}
```

What do you guys think? If I would create a pr with some of these logging "issues" fixed is that something that you would accept into this code?

**Comment by waldekmastykarz** [comment]
Thanks for the suggestion @svrooij. When looking at possible areas for improvements, let's be mindful of a few things:

- Dev Proxy is cross-platfrom, so we need to use x-plat EOLs, rather than assuming `\r\n`
- If we splat multiple statements into one, they'll show up as one message in Chrome DevTools. Let's verify that they'll be still legible. I don't think it would apply to the examples you've shared, but I thought I'd mention it in case you'd want to have a look at messages coming from plugins too.

**Comment by svrooij** [comment]
@waldekmastykarz When I created this issue I assumed that you where using the `ILogger` from **Microsoft.Extensions.Logging**, which would support actual structured logging, but instead this project has this:

https://github.com/microsoft/dev-proxy/blob/df28158bb1aea4d96653db95c39f190478aa75a4/dev-proxy-abstractions/ILogger.cs

As in building yet another logging abstraction.... When promoting developer best practices, I would not start creating my own logger abstraction, feeling a bit disappointed now.

**Comment by svrooij** [comment]
I'll try to start with it today. I have some pointers on how to do it.

But there is already dependency injection right?

**Comment by waldekmastykarz** [comment]
I don't think we use dependency injection at the moment. Right now, we support only one sink, which is the console. I suggest that we stay in scope. Your original proposal was to improve logging messages. Let's start with that. We can revisit logging implementation in the future if we get a need for it.

**Comment by waldekmastykarz** [comment]
Hey @svrooij, are you still working on this?

**Comment by svrooij** [comment]
I'll give it a go tomorrow. Got some ideas on how to get started. You done a bunch off work customizing the output, not sure if that would also be possible with structured logging.

Translating messages would be a bunch easier though, not sure if that is even on the roadmap.

**Comment by waldekmastykarz** [comment]
> Translating messages would be a bunch easier though, not sure if that is even on the roadmap.
> A format like `New Dev Proxy version {version} is available.` might be translated into `Er is een nieuwe Dev Proxy versie {version} beschikbaar.`

We don't have any plans to work on localization at the moment.

**Comment by svrooij** [comment]
Next up is using [Compile-time generated log messages](https://learn.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator#basic-usage).
