### ISSUE TITLE
[BUG]: photo requests in batch request not returning 429

### ISSUE THREAD

**Issue by MrCodeWeaver** [microsoft/dev-proxy#446]
### Description

requests in batch requests returning 502 instead of expected 429

### Expected behaviour

Expected behavior is that both back requests would return 429

### Actual behaviour

Actualy behavior is that both batch requests return 502 BadGateway No mock response found for this request

### Steps to reproduce

Repo steps:

1. download and install the latest dev proxy (v0.13.0)
2. run proxy with `devproxy --allowed-errors 429 --failure-rate 100 --no-mocks`
3. send batch request with these requests (change userGuid to an actual user id)
`   "requests": [
        {
            "url": "/users/{userGuid}/photos/120x120/$value",
            "method": "GET",
            "id": "1"
        },
        {
            "url": "/users/{userGuid}/photos/120x120/$value",
            "method": "GET",
            "id": "2"
        }
    ]
`

### Dev Proxy Version

0.13.0

### Operating system (environment)

Windows

### Shell

cmd

**Comment by waldekmastykarz** [comment]
Thank you for the info and sorry to hear you're running into trouble. Could you also please share with us your proxy config file (devproxyrc.json by default)?

**Comment by MrCodeWeaver** [comment]
[devproxyrc.json](https://github.com/microsoft/dev-proxy/files/13730039/devproxyrc.json)

**Comment by waldekmastykarz** [comment]
I can reproduce your issue, and seems to be caused by the `GraphMocksResponsePlugin` which is defined before the `GraphRandomErrorPlugin` and which fails all unmocked requests. This is clearly a bug that we'll fix asap. For now, you can work around it by disabling the `GraphMockResponsePlugin`.

**Comment by waldekmastykarz** [comment]
Looking at it some more... We implemented forcefully failing unmocked requests inside a batch, because we can't pass only some of them to Graph. So we can either mock all requests inside a batch or none and we decided to forcefully fail unmocked requests. You can solve it in two ways:

1. If you're not using mocking, disable the `GraphMockResponsePlugin`
1. If you want to use mocking along with `GraphRandomErrorPlugin`, exclude the $batch endpoint from mocking:

```json
{
  "name": "GraphMockResponsePlugin",
  "enabled": true,
  "pluginPath": "~appFolder\\plugins\\dev-proxy-plugins.dll",
  "configSection": "mocksPlugin",
  "urlsToWatch": [
    "!https://graph.microsoft.com/v1.0/$batch",
    "!https://graph.microsoft.com/beta/$batch",
    "https://graph.microsoft.com/v1.0/*",
    "https://graph.microsoft.com/beta/*",
    "https://graph.microsoft.us/v1.0/*",
    "https://graph.microsoft.us/beta/*",
    "https://dod-graph.microsoft.us/v1.0/*",
    "https://dod-graph.microsoft.us/beta/*",
    "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
    "https://microsoftgraph.chinacloudapi.cn/beta/*",
    "https://*.sharepoint.*/*_api/*",
    "https://*.sharepoint.*/*_vti_bin/*",
    "https://*.sharepoint-df.*/*_api/*",
    "https://*.sharepoint-df.*/*_vti_bin/*"
  ]
}
```

I hope this helps. Thanks again for reaching out to us

**Comment by MrCodeWeaver** [comment]
Ok thanks for the responses. Yes when I disable the `GraphMockResponsePlugin` then I am getting 429s.

I guess I was expecting that if I include the command line argument of `--no-mocks` then it should not forcefully fail unmocked requests

**Comment by waldekmastykarz** [comment]
> I guess I was expecting that if I include the command line argument of `--no-mocks` then it should not forcefully fail unmocked requests

Ah, you're right. Sorry, I missed that. Yes, `--no-mocks` should disable the `GraphMockResponsePlugin` just as you'd expect. That's a bug.
