### ISSUE TITLE
[BUG]: Dev Proxy DevToolsPlugin for `Chrome` does not work

### ISSUE THREAD

**Issue by Adam-it** [microsoft/dev-proxy#468]
### Description

So I configured proxy `devproxyrc.json` to use the DevToolsPlugin.
```
....
"plugins": [
....
   {
      "name": "DevToolsPlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "devTools"
    }
  ],
  "devTools": {
    "preferredBrowser": "Chrome"
  },
....
```
and then after I try to run dev proxy I get the following error
![image](https://github.com/microsoft/dev-proxy/assets/58668583/0df41163-717f-4d9f-8aba-6b8e5a1e7fd8)

I have Chrome installed. Not sure what I am doing wrong 🤔

### Expected behaviour

I would expect that after that configuration and running `devproxy` Chrome would open with devtools

### Actual behaviour

I get the following message in the console
```
DevTools available at http://localhost:9222/devtools/inspector.html?ws=localhost:51710
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'chrome.exe' with working directory 'C:\workspace\devproxy'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Microsoft.DevProxy.Plugins.Inspection.DevToolsPlugin.InitInspector()
   at Microsoft.DevProxy.Plugins.Inspection.DevToolsPlugin.Register(IPluginEvents pluginEvents, IProxyContext context, ISet`1 urlsToWatch, IConfigurationSection configSection)
   at Microsoft.DevProxy.PluginLoader.LoadPlugins(IPluginEvents pluginEvents, IProxyContext proxyContext)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
   ```

### Steps to reproduce

1. install latest devproxy
2. modify `devproxyrc.json` adding this to plugins
```
{
      "name": "DevToolsPlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "devTools"
    }
```

3. modify `devproxyrc.json` setting:
```
 "devTools": {
    "preferredBrowser": "Chrome"
  }
```

4. run `devproxy --no-mocks --log-level Info --failure-rate 0`

### Dev Proxy Version

0.13.0

### Operating system (environment)

Windows

### Shell

PowerShell

### Configuration file

{
  "plugins": [
    {
      "name": "DevToolsPlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "devTools"
    },
    {
      "name": "LatencyPlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "latencyPlugin"
    },
    {
      "name": "RetryAfterPlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll"
    },
    {
      "name": "GraphSelectGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "urlsToWatch": [
        "https://graph.microsoft.com/v1.0/*",
        "https://graph.microsoft.com/beta/*",
        "https://graph.microsoft.us/v1.0/*",
        "https://graph.microsoft.us/beta/*",
        "https://dod-graph.microsoft.us/v1.0/*",
        "https://dod-graph.microsoft.us/beta/*",
        "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
        "https://microsoftgraph.chinacloudapi.cn/beta/*"
      ]
    },
    {
      "name": "ODSPSearchGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "urlsToWatch": [
        "https://graph.microsoft.com/v1.0/*",
        "https://graph.microsoft.com/beta/*",
        "https://graph.microsoft.us/v1.0/*",
        "https://graph.microsoft.us/beta/*",
        "https://dod-graph.microsoft.us/v1.0/*",
        "https://dod-graph.microsoft.us/beta/*",
        "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
        "https://microsoftgraph.chinacloudapi.cn/beta/*"
      ]
    },
    {
      "name": "GraphBetaSupportGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "urlsToWatch": [
        "https://graph.microsoft.com/beta/*",
        "https://graph.microsoft.us/beta/*",
        "https://dod-graph.microsoft.us/beta/*",
        "https://microsoftgraph.chinacloudapi.cn/beta/*"
      ]
    },
    {
      "name": "GraphSdkGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "urlsToWatch": [
        "https://graph.microsoft.com/v1.0/*",
        "https://graph.microsoft.com/beta/*",
        "https://graph.microsoft.us/v1.0/*",
        "https://graph.microsoft.us/beta/*",
        "https://dod-graph.microsoft.us/v1.0/*",
        "https://dod-graph.microsoft.us/beta/*",
        "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
        "https://microsoftgraph.chinacloudapi.cn/beta/*"
      ]
    },
    {
      "name": "ODataPagingGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll"
    },
    {
      "name": "GraphClientRequestIdGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "urlsToWatch": [
        "https://graph.microsoft.com/v1.0/*",
        "https://graph.microsoft.com/beta/*",
        "https://graph.microsoft.us/v1.0/*",
        "https://graph.microsoft.us/beta/*",
        "https://dod-graph.microsoft.us/v1.0/*",
        "https://dod-graph.microsoft.us/beta/*",
        "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
        "https://microsoftgraph.chinacloudapi.cn/beta/*"
      ]
    },
    {
      "name": "CachingGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "cachingGuidance"
    },
    {
      "name": "RateLimitingPlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "rateLimiting"
    },
    {
      "name": "MockResponsePlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "mocksPlugin"
    },
    {
      "name": "GraphMockResponsePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "mocksPlugin"
    },
    {
      "name": "GraphRandomErrorPlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "graphRandomErrorsPlugin"
    },
    {
      "name": "ExecutionSummaryPlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "executionSummaryPlugin"
    },
    {
      "name": "MinimalPermissionsPlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "minimalPermissionsPlugin"
    },
    {
      "name": "MinimalPermissionsGuidancePlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll"
    },
    {
      "name": "MockGeneratorPlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll"
    },
    {
      "name": "DevToolsPlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "devTools"
    }
  ],
  "devTools": {
    "preferredBrowser": "Chrome"
  },
  "urlsToWatch": [
    "https://graph.microsoft.com/v1.0/*",
    "https://graph.microsoft.com/beta/*",
    "https://graph.microsoft.us/v1.0/*",
    "https://graph.microsoft.us/beta/*",
    "https://dod-graph.microsoft.us/v1.0/*",
    "https://dod-graph.microsoft.us/beta/*",
    "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
    "https://microsoftgraph.chinacloudapi.cn/beta/*",
    "https://*.sharepoint.*/*_api/*",
    "https://*.sharepoint.*/*_vti_bin/*",
    "https://*.sharepoint-df.*/*_api/*",
    "https://*.sharepoint-df.*/*_vti_bin/*"
  ],
  "mocksPlugin": {
    "mocksFile": "responses.json"
  },
  "graphRandomErrorsPlugin": {
    "allowedErrors": [ 429, 500, 502, 503, 504, 507 ]
  },
  "executionSummaryPlugin": {
    "groupBy": "url"
  },
  "minimalPermissionsPlugin": {
    "type": "delegated"
  },
  "cachingGuidance": {
    "cacheThresholdSeconds": 5
  },
  "latencyPlugin": {
    "minMs": 200,
    "maxMs": 10000
  },
  "rateLimiting": {
    "costPerRequest": 2,
    "rateLimit": 120,
    "retryAfterSeconds": 5
  },
  "rate": 50,
  "labelMode": "text",
  "logLevel": "info"
}

**Comment by garrytrinder** [comment]
Apologies for the trouble @Adam-it

Have you tried using either `Edge` or `EdgeDev`? Do you get the same issue?

**Comment by Adam-it** [comment]
> Apologies for the trouble @Adam-it
> 
> Have you tried using either `Edge` or `EdgeDev`? Do you get the same issue?


No problem. Software is software and it's natural to have bugs. Or it is something I done wrong 😅
Anyway 😉
Yes I tired Edge. I got a bit further down the road but then it also did not work. I opened a separate issue for that 😅.
Sorry for creating się much trouble

**Comment by waldekmastykarz** [comment]
How did you install Chrome @Adam-it? Can you start it from the run dialog (Win+R > chrome)?

**Comment by Adam-it** [comment]
> How did you install Chrome @Adam-it? Can you start it from the run dialog (Win+R > chrome)?

I installed it using the typical web installer that you get when you visit the chrome download page.
I will check today over the night and let you know

**Comment by waldekmastykarz** [comment]
I can repro the issue. Will fix. Sorry for the trouble
