### ISSUE TITLE
[BUG]: running `devproxy --version` with `DevToolsPlugin` configured start the browser

### ISSUE THREAD

**Issue by Adam-it** [microsoft/dev-proxy#469]
### Description

running `devproxy --version` with `DevToolsPlugin` configured start the browser but I think should just present the version

### Expected behaviour

running `devproxy --version` with `DevToolsPlugin` should just present the version without starting the browser 

### Actual behaviour

starts the browser and presents this 
![image](https://github.com/microsoft/dev-proxy/assets/58668583/4148eb0d-13bb-41d0-bf1a-d0256fe70ec5)

### Steps to reproduce

1. install Dev Proxy
2. Configure DevToolsPlugin following the guide for `Edge` as browser
3. run `devproxy --version`

### Dev Proxy Version

0.13.0

### Operating system (environment)

Windows

### Shell

PowerShell

### Configuration file

{
  "plugins": [
    {
      "name": "DevToolsPlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "devTools"
    },
    {
      "name": "LatencyPlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "latencyPlugin"
    },
    {
      "name": "RetryAfterPlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll"
    },
    {
      "name": "GraphSelectGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "urlsToWatch": [
        "https://graph.microsoft.com/v1.0/*",
        "https://graph.microsoft.com/beta/*",
        "https://graph.microsoft.us/v1.0/*",
        "https://graph.microsoft.us/beta/*",
        "https://dod-graph.microsoft.us/v1.0/*",
        "https://dod-graph.microsoft.us/beta/*",
        "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
        "https://microsoftgraph.chinacloudapi.cn/beta/*"
      ]
    },
    {
      "name": "ODSPSearchGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "urlsToWatch": [
        "https://graph.microsoft.com/v1.0/*",
        "https://graph.microsoft.com/beta/*",
        "https://graph.microsoft.us/v1.0/*",
        "https://graph.microsoft.us/beta/*",
        "https://dod-graph.microsoft.us/v1.0/*",
        "https://dod-graph.microsoft.us/beta/*",
        "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
        "https://microsoftgraph.chinacloudapi.cn/beta/*"
      ]
    },
    {
      "name": "GraphBetaSupportGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "urlsToWatch": [
        "https://graph.microsoft.com/beta/*",
        "https://graph.microsoft.us/beta/*",
        "https://dod-graph.microsoft.us/beta/*",
        "https://microsoftgraph.chinacloudapi.cn/beta/*"
      ]
    },
    {
      "name": "GraphSdkGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "urlsToWatch": [
        "https://graph.microsoft.com/v1.0/*",
        "https://graph.microsoft.com/beta/*",
        "https://graph.microsoft.us/v1.0/*",
        "https://graph.microsoft.us/beta/*",
        "https://dod-graph.microsoft.us/v1.0/*",
        "https://dod-graph.microsoft.us/beta/*",
        "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
        "https://microsoftgraph.chinacloudapi.cn/beta/*"
      ]
    },
    {
      "name": "ODataPagingGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll"
    },
    {
      "name": "GraphClientRequestIdGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "urlsToWatch": [
        "https://graph.microsoft.com/v1.0/*",
        "https://graph.microsoft.com/beta/*",
        "https://graph.microsoft.us/v1.0/*",
        "https://graph.microsoft.us/beta/*",
        "https://dod-graph.microsoft.us/v1.0/*",
        "https://dod-graph.microsoft.us/beta/*",
        "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
        "https://microsoftgraph.chinacloudapi.cn/beta/*"
      ]
    },
    {
      "name": "CachingGuidancePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "cachingGuidance"
    },
    {
      "name": "RateLimitingPlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "rateLimiting"
    },
    {
      "name": "MockResponsePlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "mocksPlugin"
    },
    {
      "name": "GraphMockResponsePlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "mocksPlugin"
    },
    {
      "name": "GraphRandomErrorPlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "graphRandomErrorsPlugin"
    },
    {
      "name": "ExecutionSummaryPlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "executionSummaryPlugin"
    },
    {
      "name": "MinimalPermissionsPlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "minimalPermissionsPlugin"
    },
    {
      "name": "MinimalPermissionsGuidancePlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll"
    },
    {
      "name": "MockGeneratorPlugin",
      "enabled": false,
      "pluginPath": "plugins\\dev-proxy-plugins.dll"
    },
    {
      "name": "DevToolsPlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll",
      "configSection": "devTools"
    }
  ],
  "devTools": {
    "preferredBrowser": "Edge"
  },
  "urlsToWatch": [
    "https://graph.microsoft.com/v1.0/*",
    "https://graph.microsoft.com/beta/*",
    "https://graph.microsoft.us/v1.0/*",
    "https://graph.microsoft.us/beta/*",
    "https://dod-graph.microsoft.us/v1.0/*",
    "https://dod-graph.microsoft.us/beta/*",
    "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
    "https://microsoftgraph.chinacloudapi.cn/beta/*",
    "https://*.sharepoint.*/*_api/*",
    "https://*.sharepoint.*/*_vti_bin/*",
    "https://*.sharepoint-df.*/*_api/*",
    "https://*.sharepoint-df.*/*_vti_bin/*"
  ],
  "mocksPlugin": {
    "mocksFile": "responses.json"
  },
  "graphRandomErrorsPlugin": {
    "allowedErrors": [ 429, 500, 502, 503, 504, 507 ]
  },
  "executionSummaryPlugin": {
    "groupBy": "url"
  },
  "minimalPermissionsPlugin": {
    "type": "delegated"
  },
  "cachingGuidance": {
    "cacheThresholdSeconds": 5
  },
  "latencyPlugin": {
    "minMs": 200,
    "maxMs": 10000
  },
  "rateLimiting": {
    "costPerRequest": 2,
    "rateLimit": 120,
    "retryAfterSeconds": 5
  },
  "rate": 50,
  "labelMode": "text",
  "logLevel": "info"
}

**Comment by Adam-it** [comment]
Ye, and seems like a easy fix. To you accept help from the community? I would gladly help out 🙂

**Comment by garrytrinder** [comment]
Actually, this is wider than just the `DevToolsPlugin` it also occurs when you have the `GenericRandomError` plugin enabled. See below where I have both enabled.

![image](https://github.com/microsoft/dev-proxy/assets/11563347/92a529c1-a2ec-47d2-a177-a69710364467)

**Comment by garrytrinder** [comment]
Good shout @waldekmastykarz 

Subcommands do have the same issue

![image](https://github.com/microsoft/dev-proxy/assets/11563347/87628dcb-7f59-4656-bb51-b244011543e4)

**Comment by Adam-it** [comment]
@garrytrinder, @waldekmastykarz 
when I have the `DevToolsPlugin` configured and running the `devproxy --help` also starts the browser 🙂

![image](https://github.com/microsoft/dev-proxy/assets/58668583/db0dfead-4d78-46e2-a6bb-676d8b0455af)

seems like a very similar case. @garrytrinder would you be so kind to also double check that? Do you want a separate issue for that or we could track it here as well? Seems like a similar behavior to me and I do not whish to create a mess in the issue list 🙂

**Comment by waldekmastykarz** [comment]
I think we captured that already. Also the fact that plugins run on subcommands while they shouldn't. We're going to fix it asap. Thank you for reporting it
