### ISSUE TITLE
it should be 'Icon' not 'Icons' 

### ISSUE THREAD

**Issue by Adam-it** [microsoft/dev-proxy#472]
### Type of issue

Typo

### Feedback

On the page we may read 
![image](https://github.com/microsoft/dev-proxy/assets/58668583/3a23be7f-1637-4e51-99a3-0618c55294c1)
But when we check the enum in code we see
![image](https://github.com/microsoft/dev-proxy/assets/58668583/f5c4e820-5a23-4761-835a-0fd1fb3d3d79)

So actually it should be `icon` as the value in the enum. `icons` will not work and result as an error when starting the proxy

![ItsLeviosaNotLeviosarGIF](https://github.com/microsoft/dev-proxy/assets/58668583/99fd985f-b881-43c4-8639-e6f92dd96726)

😁
cheers

### Page URL

https://learn.microsoft.com/en-us/microsoft-cloud/dev/dev-proxy/how-to/change-console-output-to-use-icons

### Content source URL

https://github.com/MicrosoftDocs/microsoft-cloud/blob/main/docs/dev/dev-proxy/how-to/change-console-output-to-use-icons.md

### Author

@garrytrinder

### Document Id

04152b8a-8306-6fbd-b45b-06502ede828b

**Comment by waldekmastykarz** [comment]
I've got a PR merged already. Waiting for it to be released
