### ISSUE TITLE
Improve plugin setup

### ISSUE THREAD

**Issue by Adam-it** [microsoft/dev-proxy#473]
Currently (like in many other configure cases) if we want to setup some custom or predefined plugin to the proxy we need to modify the `devproxyrc.json`. 
This seems kinda hacky experience and when working with the proxy in a larger group I noticed many had problems with setting this up properly. For example, some were using a simple notepad to modify the JSON and made simple mistakes like missed `,` when adding a new array item, or extended the JSON in wrong place.

So I got a couple of ideas (smaller and bigger once) that might bring improvements to this experience:

1. introduce a command in the devproxy (similar to `msgraphdb` command) which will open the `devproxyrc.json` in user default app to modify .json files. Something like ` devproxy settings`. Why? ... well you wouldn't believe how many questions on teams I got like "hey, where may I find the `devproxyrc.json`?" 🙂
2. introduce a json schema which will introduce validation that is specific to devproxy json format. Add it in the default `devproxyrc.json`. So that when someone will open it in VS Code (or something better than notepad 😉), then he or she will get additional inteli when modifying the .json file
3. this is gonna be a hard one but I IMO 😋 it is an awesome suggestion. Introduce a command (or commands) that will modify the `devproxyrc.json` for the user. 
For example, running a command like `devproxy plugin --name DevToolsPlugin` would automatically for the user to extend the json with 
```
{
  "name": "DevToolsPlugin",
  "enabled": true,
  "pluginPath": "plugins\\dev-proxy-plugins.dll",
  "configSection": "devTools"
}
```
and running the command should also prompt the user for plugin-specific data like 
```
please provide value for:
preferredBrowser?
```

And introduce a similar command which will allow to modify the  `devproxyrc.json` with a custom plugin. Something like 
 `devproxy customplugin --name myCustomgPlugin --pluginPath 'myCustomgPluginPathToDll' --enabled --configSection 'customPlugin' --config '{"customPlugin": "def"}'`
 and the result of running this command should be
 ```
 {
  "plugins": [
.....,
    {
      "name": "myCustomgPlugin",
      "enabled": true
      "pluginPath": "myCustomgPluginPathToDll",
      "configSection": "customPlugin"
    }
  ],
  "customPlugin": "def",
  ....
}
 ```
 
Let me know what you think 🙂. Cheers 👍

**Comment by waldekmastykarz** [comment]
Awesome suggestion. Schema is the low hanging fruit and we've got it already in the latest beta.

Config wizard would be awesome. Each plugin would need to implement it itself because each one has distinct options. I'm also concerned about how we'd handle complex configuration like mocks. Let us think about it some more.

**Comment by waldekmastykarz** [comment]
> 1. introduce a command in the devproxy (similar to `msgraphdb` command) which will open the `devproxyrc.json` in user default app to modify .json files. Something like ` devproxy settings`. Why? ... well you wouldn't believe how many questions on teams I got like "hey, where may I find the `devproxyrc.json`?" 🙂

I think it would be better to get the default editor rather than the default app. I wonder how many folks associate .json files with their editor. Isn't the default opening them in a browser which would be useless?

**Comment by Adam-it** [comment]
not actually sure what is the default default as I already changed it.🤔 But if it is indeed a browser then yes, it is useless 🙂

**Comment by waldekmastykarz** [comment]
We've just introduced a new command named `devproxy config` which opens the default/current devproxyrc.json file in the associated editor #806. It works pretty cool. You're right all along ❤️

**Comment by waldekmastykarz** [comment]
As for your suggestion to help folks enable plugins, we recommend using the [Dev Proxy Toolkit](https://marketplace.visualstudio.com/items?itemName=garrytrinder.dev-proxy-toolkit) which provides you preconfigured snippets and deeplinks to docs to more information about plugins.

Since we addressed all your suggestions, I'm going to close this issue. Thanks again for working with us!
