### ISSUE TITLE
Add chmod post install tasks to script

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#479]
When setting up proxy on macOS we ask you to

> 1. Make files executable. Open the devproxy installation folder in a terminal. Execute chmod -x devproxy and then chmod -x libe_sqlite3.dylib

Now that we have the setup script for macOS we should include these steps in the script to reduce the steps developers need to take to get started with proxy.

**Comment by bcage29** [comment]
@garrytrinder the install instructions should be chmod +x devproxy and chmod +x libe_sqlite3.dylib. The documentation has the '-' instead of the '+' sign.

**Comment by waldekmastykarz** [comment]
`chmod +x devproxy` is already there. Will add `libe_sqlite3.dylib` to it

**Comment by waldekmastykarz** [comment]
I updated the docs and the change should be visible in the next few hours. Thanks again for bringing it up @bcage29 👏

**Comment by bcage29** [comment]
@waldekmastykarz @garrytrinder I was following the guide here https://learn.microsoft.com/en-us/microsoft-cloud/dev/dev-proxy/get-started and it has the '-' signs. I tried to edit the page, but it took me to a 404 page.
