### ISSUE TITLE
Move updating the MSGraph DB to the SelectGuidancePlugin

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#481]
We should move updating the MSGraph DB to the SelectGuidancePlugin. Right now, we update the DB on each Dev Proxy start, while the database is only used by the SelectGuidancePlugin, which is disabled by default. We should update the DB on the plugin registration instead which will eliminate the overhead for folks who don't use Dev Proxy with Microsoft Graph.

**Comment by garrytrinder** [comment]
Great idea and will help with perf on start-up for non M365 scenarios 🚀
