### ISSUE TITLE
Refactor ProxyHttpEventArgsBase to move throttled requests to pluginData

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#507]
As we've introduced pluginData in ProxyEngine in #506, let's see if we can refactor ProxyHttpEventArgsBase and move throttled requests from its constructor into pluginData. Throttling belongs to plugins and shouldn't be explicitly exposed in the engine or event args.

**Comment by waldekmastykarz** [comment]
Moving information about the throttled requests to pluginData wouldn't be natural. Right now, plugin data is tied to session (single request+response). On the other hand, throttled requests apply as long as proxy is running. As such, it would be clearer to:

1. Rename pluginData to sessionData, to clearly indicate that the data is tied to a single session
1. Add globalData (or choose a more suitable name), for storing data that span multiple sessions.

Thoughts @garrytrinder?

**Comment by garrytrinder** [comment]
I agree with the approach. 

In terms of naming, in the HTTP spec a request\response is referred to as an `exchange`, see https://www.rfc-editor.org/rfc/rfc2616#section-1.4

How about we use `exchangeData`, to store data for request/response exchanges and `sessionData` which refers to the Proxy session itself.

**Comment by waldekmastykarz** [comment]
To be honest, without knowing the spec, if I just looked at `exchangeData`, I'd have no idea what it's referring to. So I suggest we consider a different name. As for `sessionData`, Titanium uses it for a request session, so I suggest we align with it, because if we use it for proxy session it'll be confusing for others who don't have this background.
