### ISSUE TITLE
Create a proxy upgrade script

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#512]
Right now, when we release a new version of proxy, customers who work with an older version, get the following message:

![image](https://github.com/microsoft/dev-proxy/assets/11164679/99e85c1d-8519-4c5d-adc0-6d6207ffd6e6)

It would be easier for them to upgrade to get a command to run (similar to our install script) rather than navigate to a link and upgrade manually.

Things we need to factor in:

- current shell so that we know whether to show a PowerShell or a bash script
- customer's proxy installation directory
- possible changes to devproxyrc.json which we should back-up (or should we backup the whole folder?)

Tasks:

- [ ] Create bash upgrade script
- [ ] Create PowerShell upgrade script
- [ ] Update new version notification in Dev Proxy to show the upgrade script to run

**Comment by SilentSobs** [comment]
Hello, I'm interested in contributing to this issue.

**Comment by waldekmastykarz** [comment]
Awesome! We appreciate your help! Please, don't hesitate to reach out if you have any questions

**Comment by SilentSobs** [comment]
Yea, sure!. I'm finishing up a few more changes and fixes. I plan to submit the pull request tomorrow.

**Comment by SilentSobs** [comment]
```
private static Assembly? _assembly;
internal static Assembly GetAssembly()
    => _assembly ??= (Assembly.GetEntryAssembly() ?? Assembly.GetExecutingAssembly());
```
Could you help me understand why Assembly.GetEntryAssembly() is used first and then falls back to Assembly.GetExecutingAssembly() if it's null? What situations or scenarios are these covering?



Additionally, I noticed that the ProductVersion property retrieves the product version using the assembly details:

```
public static string ProductVersion
{
    get
    {
        if (_productVersion == string.Empty)
        {
            var assembly = GetAssembly();
            var assemblyVersionAttribute = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>();

            if (assemblyVersionAttribute is null)
            {
                _productVersion = assembly.GetName().Version?.ToString() ?? "";
            }
            else
            {
                _productVersion = assemblyVersionAttribute.InformationalVersion;
            }
        }

        return _productVersion;
    }
}

```

My main curiosity lies in understanding how the assembly details are being leveraged to determine the product version. Specifically, how does the assembly acquire the version of DevProxy?

**Comment by waldekmastykarz** [comment]
This logic is not relevant to this issue. This issue is about building an upgrade script that's upgrades the currently installed version to the latest stable/beta (depending on the user's preference). New version detection logic is out of scope and should remain as-is.

**Comment by SilentSobs** [comment]
Powershell script 

```



# Specify the path to the Dev Proxy installation directory
$devProxyPath = $PSScriptRoot

# Check if Dev Proxy is installed
if (Test-Path -Path $devProxyPath) {
    # Backup devproxyrc.json 
    Copy-Item -Path "$devProxyPath\devproxyrc.json" -Destination "$devProxyPath\devproxyrc_backup.json" -Force

    try {
        # Download and install the updated version
        $updateScript = Invoke-WebRequest -Uri "https://aka.ms/devproxy/setup.ps1"
        Invoke-Expression -Command $updateScript.Content

        Add-Type -AssemblyName System.Windows.Forms
        [System.Windows.Forms.SendKeys]::SendWait("y")
    } catch {
        Write-Host "Error occurred during installation: $_"
    }

    Write-Host "Dev Proxy has been updated successfully."
} else {
    Write-Host "Dev Proxy is not installed. Please install it first."
}

```

**Comment by waldekmastykarz** [comment]
> $devProxyPath = $PSScriptRoot

We shouldn't assume that proxy is installed in the current directory. Instead, let's get the actual location

> Copy-Item -Path "$devProxyPath\devproxyrc.json" -Destination "$devProxyPath\devproxyrc_backup.json" -Force

We should also back up other files, because people might have in their custom presets, plugins, etc.



> Add-Type -AssemblyName System.Windows.Forms
>         [System.Windows.Forms.SendKeys]::SendWait("y")

Does this work on all platforms?

> $updateScript = Invoke-WebRequest -Uri "https://aka.ms/devproxy/setup.ps1"

We should consider here, that folks might be subscribed to beta updates, and want to install the latest beta instead of stable. Check out the [`newVersionNotification` option](https://learn.microsoft.com/en-us/microsoft-cloud/dev/dev-proxy/technical-reference/proxy-settings) in proxy config.

**Comment by SilentSobs** [comment]
#558

**Comment by waldekmastykarz** [comment]
I'm not quite sure what the issue is that you're referring to. If I run the current script, it seems to be detecting the Windows version just fine:

<img width="947" alt="image" src="https://github.com/microsoft/dev-proxy/assets/11164679/5f526dbe-a087-4852-9718-f76047b19744">

**Comment by SilentSobs** [comment]
The command $PSVersionTable.OS might not be providing any output because it's not available for PowerShell version 5.1. My PowerShell version is still 5.1, and I noticed this while trying to create a script

**Comment by SilentSobs** [comment]
![image](https://github.com/microsoft/dev-proxy/assets/157403288/3a330dc2-5175-4ba3-b882-7086bde83dc0)
This command only works in PowerShell versions 6 ``` $PSVersionTable.PSVersion  ``` and above, and since many people are still using PowerShell version 5.1, we need to fix this

**Comment by SilentSobs** [comment]
We should go with ```[Environment]::OSVersion.VersionString``` to detect os it will work in both PowerShell 5 and versions above 6

**Comment by waldekmastykarz** [comment]
Also, let's take updating the setup script in a separate issue

**Comment by SilentSobs** [comment]
> We haven't tested the script in Windows PowerShell and assumed Microsoft PowerShell so far. Is that the only thing that's not working in Windows PowerShell?

Yes.

![image](https://github.com/microsoft/dev-proxy/assets/157403288/106d74d2-7b10-4761-8541-a4ae05803957)

![image](https://github.com/microsoft/dev-proxy/assets/157403288/f04abc6b-cbed-480d-9abe-2a111fc0be2f)

**Comment by SilentSobs** [comment]
> We haven't tested the script in Windows PowerShell and assumed Microsoft PowerShell so far. Is that the only thing that's not working in Windows PowerShell?

We can replace the first 'if' statement with the following:
 ```
 if ($os -like "*Windows*") {
    if ($arch -eq "64-bit") {
        $url = "$base_url-win-x64-$version.zip"
    } elseif ($arch -eq "32-bit") {
        $url = "$base_url-win-x86-$version.zip"
    } else {
        Write-Host "Unsupported architecture $arch. Aborting"
        exit 1
    }
    Write-Host "Downloading Dev Proxy version $version..."
} 
```

Which is working on Microsoft PowerShell 5, and I think it will also work in PowerShell 7. Can you please test? I don't have PowerShell 7.

**Comment by waldekmastykarz** [comment]
If I run the command on PowerShell on macOS, I'm getting the following output:

<img width="896" alt="image" src="https://github.com/microsoft/dev-proxy/assets/11164679/d7d628fa-6060-4894-877e-0f0a80fd67da">

Seems like the way to detect the OS that you're proposing considers macOS linux which isn't helpful and I don't think we can use it. I suggest that we stick with the current script and for automated installs only support Microsoft PowerShell.

**Comment by SilentSobs** [comment]
Okay, I was not aware that PowerShell is also available on macOS. Is the script we are working on not intended for Windows 10 PowerShell with version 5?

**Comment by waldekmastykarz** [comment]
Windows PowerShell (v <= 5) is available only on Windows. Microsoft PowerShell (v >= 6) is cross-platform and works on Windows, macOS and Linux. Right now, we support installations using Microsoft PowerShell.

**Comment by waldekmastykarz** [comment]
Hey @SilentSobs, are you still working on this?

**Comment by SilentSobs** [comment]
Yes.I Will make a pull request soon.

**Comment by SilentSobs** [comment]
I was having exams am working on this. sorry for delay

**Comment by SilentSobs** [comment]
I'd like to share what I've accomplished so far and gather some suggestions to ensure I'm on the right track. Currently, 

```
var newReleaseInfo = await UpdateNotification.CheckForNewVersion();
if (newReleaseInfo != null)
{
```

if it's not null then it means that there is updated version available. After obtaining this information, I log a prompt for the user's decision:

```
_logger.LogInfo("******************Do you want to upgrade? (Y/N)************************");

```
Following this, I've created another class to manage the upgrade process. For macOS and Linux, the script execution would be similar, but beforehand, I need to detect the operating system, correct?"

**Comment by waldekmastykarz** [comment]
Thanks for sharing your progress. All our install scripts are cross-OS, so instead of detecting the OS in Dev Proxy, we should detect the shell and then prompt starting the relevant upgrade script.

**Comment by waldekmastykarz** [comment]
Hey @SilentSobs, we've just released Dev Proxy on Homebrew, and will be removing macOS-specific instructions from all setup scripts. We're also working on an MSI for installation on Windows. When it's ready, it'll replace the PowerShell setup script that we've got now. We're closing this issue in favor of the new setup ways. Thanks again for working with us and your help.
