### ISSUE TITLE
wrong `>` symbol in the PowerShell script version for the beta version of installing devproxy

### ISSUE THREAD

**Issue by Adam-it** [microsoft/dev-proxy#549]
### Type of issue

Typo

### Feedback

in the PowerShell version of script to install the devproxy beta we have 
```
(Invoke-WebRequest https://aka.ms/devproxy/setup-beta.ps1).Content | > Invoke-Expression
```

but actually it should be 
```
(Invoke-WebRequest https://aka.ms/devproxy/setup-beta.ps1).Content | Invoke-Expression
```

the '>' is wrongly added there
![image](https://github.com/microsoft/dev-proxy/assets/58668583/431796dc-1bf3-459c-839f-5f732acfe681)

### Page URL

https://learn.microsoft.com/en-us/microsoft-cloud/dev/dev-proxy/get-started?tabs=powershell

### Content source URL

https://github.com/MicrosoftDocs/microsoft-cloud/blob/main/docs/dev/dev-proxy/get-started.md

### Author

@garrytrinder

### Document Id

9b3459ea-8df0-e888-794d-6b0aba5f337a

**Comment by waldekmastykarz** [comment]
Ouch, thanks for bringing it up. Will fix right away.

**Comment by waldekmastykarz** [comment]
PR with fix to docs has been merged and should be publicly visible in a few hours.
