### ISSUE TITLE
[Feature] Make GraphRandomErrorPlugin wait time configurable

### ISSUE THREAD

**Issue by heinrich-ulbricht** [microsoft/dev-proxy#561]
When returning throttling (429) responses currently always 5 seconds are returned.

https://github.com/microsoft/dev-proxy/blob/e439251642afb3ceafaaf24456a22dfb7365e219/dev-proxy-plugins/RandomErrors/GraphRandomErrorPlugin.cs#L37C23-L37C43

I'd like to configure this value to be e.g. 5 minutes, to simulate the more extreme cases.

**Comment by waldekmastykarz** [comment]
As far as I know, the retry-after value is always 5 seconds. The extreme case which you're referring to, would be simulated by your app being throttled for a total of several minutes, but each time with 5 seconds intervals.

**Comment by heinrich-ulbricht** [comment]
@waldekmastykarz I did not know this (implementation?) detail about MS Graph. Fair enough. What about the SharePoint API? The plugin also handles those endpoints and I suspect the rules might be different there. When CSOM calls get throttled, is the wait also always 5 seconds?

**Comment by waldekmastykarz** [comment]
As far as I know, also in SharePoint the wait time is always 5 seconds. I'll double check with the respective PGs to confirm that nothing has changed.

**Comment by heinrich-ulbricht** [comment]
@waldekmastykarz If that would be the case that the wait time is always 5 seconds, and my assumption that my app handles those waits properly holds true, then my assumption of >40 seconds waits due to throttling is probably wrong.

Thanks for checking. In the meantime I'm falling back to the more generic GenericRandomErrorPlugin as shown here: https://learn.microsoft.com/en-us/microsoft-cloud/dev/dev-proxy/how-to/test-that-my-application-handles-throttling-properly

**Comment by waldekmastykarz** [comment]
> @waldekmastykarz If that would be the case that the wait time is always 5 seconds, and assuming my app handles those waits properly, then my assumption of >40s waits due to throttling is probably wrong. But I'm pretty sure I saw wait times up to several minutes happening. Might be as penalty when not adhering to the 5s? Not sure.

My understanding was, that when throttled, you should wait for the specified period of time. If you keep sending requests, throttling will be prolonged, basically resetting the timer after each call. Let me double check if that's still the case, as our services keep evolving.

**Comment by waldekmastykarz** [comment]
It seems like the retry-after value in SPO is variable. We'll update the plugin to make it configurable. Thank you for bringing it up.

**Comment by heinrich-ulbricht** [comment]
This is well-aligned with my observations and interpretations :D

**Comment by waldekmastykarz** [comment]
We've just released a new beta version with the retry-after value in the GraphRandomErrorPlugin being configurable:

```json
{
  "graphRandomErrorsPlugin": {
    "retryAfterInSeconds": 10
  }
}
``` 

You can grab it using our [beta setup script](https://learn.microsoft.com/en-us/microsoft-cloud/dev/dev-proxy/get-started?tabs=powershell&pivots=client-operating-system-macos#install-dev-proxy).

Thanks again for bringing it up!
