### ISSUE TITLE
BUG: Generating OpenAPI specs breaks if the API uses the same response header multiple times

### ISSUE THREAD

**Issue by gghaleb** [microsoft/dev-proxy#571]
### Description

OpenAPI spec not being generated, I created my config file "devproxy.config.json" myself and placed it in my devproxy folder.
the plugin is enabled, the pluginpath correct and the urlstowatch is correct, as per the below JSON.
The request is sent using Postman (of course i added the custom proxy and port), and opening devproxy –failure-rate 0.

### Expected behaviour

Spec to be genrated in devproxy folder

### Actual behaviour

Spec is not being generated

### Steps to reproduce

I have started recording, then requesting from Postman of a Dataverse API and later stopping, the postman request is succeeding.
But the spec file that is expected to get generated inside the devproxy folder in my "C:/users/username/devproxy" folder is not there.

### Dev Proxy Version

0.15.0-beta.2

### Operating system (environment)

Windows

### Shell

cmd

### Configuration file

{
“plugins”: [
{
“name”: “OpenApiSpecGeneratorPlugin”,
“enabled”: true,
“pluginPath”: “C:/users/username/devproxy/plugins/dev-proxy-plugins.dll”
}
],
“urlsToWatch”: [
“https://orgxxxxxxxxx.api.crm3.dynamics.com/*”
]
}

**Comment by waldekmastykarz** [comment]
Thank you for reaching out to us and sorry to hear that something's not working as expected. Can you share the API request that you're executing from Postman? Also, do you see in the terminal that Dev Proxy intercepted the request?

**Comment by gghaleb** [comment]
I am noticing nothing in the terminal after the r and before the s commands,  it is a normal behaviour? Or should i see the request being intercepted on that level?

**Comment by gghaleb** [comment]
GET https://org12abc123.api.crm3.dynamics.com/api/data/v9.2/contacts?$filter=emailaddress1 eq 'someone_a@example.com'

is my request

**Comment by gghaleb** [comment]
Postman desktop latest version February 2024 (v10.23).
I disabled Proxy auth from Postman but I did not see any difference.
Dev Proxy is very well intercepting your own call (https://jsonplaceholder.typicode.com/posts) from the same Postman desktop, however it is not intercepting (https://orgxxxxxxxx.api.crm3.dynamics.com/api/data/v9.2/contacts?$filter=emailaddress1 eq 'someone_a@example.com'&$select=lastname). Do you think it is an authorization issue ? I am using OAuth 2.0 added to Request Headers  and access token.

pic showing intercepted calls for: https://jsonplaceholder.typicode.com/posts
![Capture](https://github.com/microsoft/dev-proxy/assets/40804402/a56d4675-00b3-4a04-82e4-0d65bd41318b)

**Comment by waldekmastykarz** [comment]
> Do you think it is an authorization issue ?

I don't think so. Authorization in this case means only additional headers so nothing that affects Dev Proxy intercepting the request.

When you see Dev Proxy intercept requests to `https://jsonplaceholder.typicode.com/posts`, how do you start proxy? Are you using `devproxy --config-file devproxy.config.json` (assuming you start proxy from its installation folder) or are you starting it differently? By default, Dev Proxy is looking for a config file named `devproxyrc.json`. If you use a different name, then you need to specify its name explicitly. Without it, Dev Proxy falls back to its default config in the installation folder.

**Comment by gghaleb** [comment]
OK I modified the config file devproxyrc.json and I was able to intercept my own "urlsToWatch" and added to it the following:
{
      "name": "OpenApiSpecGeneratorPlugin",
      "enabled": true,
      "pluginPath": "plugins\\dev-proxy-plugins.dll"
 }

to be able to have my spec generated. However when I stpeed recording, we received the error:

◉ Recording...
 request     GET https://orgxxxxxxxx.api.crm3.dynamics.com/api/data/v9.2/sdkmessageprocessingsteps?$select=sdkmessageprocessingstepid&$filter=_eventhandler_value%20eq%20%2773A861D1-F4C9-EE11-9079-0022483CC59F%27%20and%20description%20eq%20%27whbkS:%20Update%20of%20contact%27
     api   ╭ Passed through
           ╰ GET https://orgxxxxxxxx.api.crm3.dynamics.com/api/data/v9.2/sdkmessageprocessingsteps?$select=sdkmessageprocessingstepid&$filter=_eventhandler_value%20eq%20%2773A861D1-F4C9-EE11-9079-0022483CC59F%27%20and%20description%20eq%20%27rtgtrbrbr%20hrbrt%20of%20contact%27
○ Stopped recording

Creating OpenAPI spec from recorded requests...
  Error processing request GET https://orgxxxxxxxx.api.crm3.dynamics.com/api/data/v9.2/sdkmessageprocessingsteps?$select=sdkmessageprocessingstepid&$filter=_eventhandler_value%20eq%20%2773A861D1-F4C9-EE11-9079-0022483CC59F%27%20and%20description%20eq%20%27rtgtrbrbr%20hrbrt%20of%20contact%27: An item with the same key has already been added. Key: x-ms-service-request-id

Can you help explaining this error? we are almost there, thanks!

**Comment by waldekmastykarz** [comment]
The error you're seeing can be caused by two things:

- the API that you're using responds with multiple instances of the `x-ms-service-request-id` header
- for some reason, we fail to merge the response from Dynamics

If you look at the response headers in Postman, do you see the `x-ms-service-request-id` header multiple times?

**Comment by gghaleb** [comment]
Yes I can find two, and same for all other requests... I am checking if this is normal for Dataverse APIs. Is there a way to skip this and generate the spec?

**Comment by waldekmastykarz** [comment]
Not at the moment. While it's not typical, some APIs use the same headers multiple times. We shouldn't break on it. We'll fix it in the next few days and let you know when we've got a fix available, ok? Sorry for the trouble and I appreciate you working with us to sort it out.

**Comment by gghaleb** [comment]
thanks Waldek, looking forward to the fix.

**Comment by waldekmastykarz** [comment]
We've just released a beta version with a fix. Could you please check if it fixes the issue for you?

**Comment by gghaleb** [comment]
what is the best way to get this update? do I have to update my version?

**Comment by gghaleb** [comment]
It worked thanks Waldek

**Comment by waldekmastykarz** [comment]
Awesome! Thank you for confirming @gghaleb 👏
