### ISSUE TITLE
v0.14.1 install using wrong schema in devproxyrc.json

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#572]
When installing proxy using the script in docs, the `devproxyrc.json` file that is created is using `v1.0` but should be `v0.14.1` instead.

![image](https://github.com/microsoft/dev-proxy/assets/11563347/6280654d-5a26-413c-971b-9e4cf3b4fc44)

**Comment by waldekmastykarz** [comment]
In the latest release, the version is already set to v0.15.0 so it could be something that slipped through in the currently latest release. No action for now.
