### ISSUE TITLE
Show hotkeys on start and after clearing output

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#585]
To make hotkeys more discoverable, we should print them on proxy start and after clearing screen:

```text
hotkeys: (r)ecord, (s)top recording, (c)lear screen
```

**Comment by garrytrinder** [comment]
💯

**Comment by oleguchok** [comment]
I created small [PR](https://github.com/microsoft/dev-proxy/pull/592) to the issue. Please let me know if I should make some changes

**Comment by waldekmastykarz** [comment]
Will do! We appreciate your help!
