### ISSUE TITLE
Add how-to for creating custom plugins

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#614]
We should publish some basic documentation about creating custom plugins. At minimum we need to include basic project structure, how to properly reference Dev Proxy assemblies and how to test the plugin.

**Comment by estruyf** [comment]
Documentation for custom plugins is in progress.

**Comment by estruyf** [comment]
Documentation has been created and ready to be verified: https://github.com/MicrosoftDocs/microsoft-cloud/pull/14

**Comment by waldekmastykarz** [comment]
Shipped! 🎉
