### ISSUE TITLE
PowerShell setup script fails in Windows PowerShell

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#624]
When you try to run the PowerShell setup script in Windows PowerShell it fails with `Unsupported OS . Aborting`. This is caused by Windows PowerShell not supporting `$PSVersionTable.OS` which we use to detect the OS. We need to either update the setup script to use an alternative way of detecting the OS or show a clear error message that Windows PowerShell is not supported and you should use Microsoft PowerShell instead. If we can't support Windows PowerShell, we should also include it in our docs.

**Comment by rutgersmit** [comment]
Stumbled upon this error this morning, thought it was because I was running it on a virtualised Windows 11 on a MacBook Air (Parallels). OS identifies itself as an ARM version. Tried this approach due to #609 

Accidentally made a pr on the original repo, wanted to merge it into my own main first.

**Comment by rutgersmit** [comment]
Was working on a better pr and then saw you did exactly the same :)
I lowercased the OSDescription because you never know right?

Thanks for the fix!

**Comment by waldekmastykarz** [comment]
> Was working on a better pr and then saw you did exactly the same :) I lowercased the OSDescription because you never know right?
> 
> Thanks for the fix!

Sorry I went over your PR: we needed the fix sooner for an experiment that we're running and I didn't want to push you on a our timeline. Once again, thank you for working with us, we appreciate your help.
