### ISSUE TITLE
Feature request: store mock response in a separate file

### ISSUE THREAD

**Issue by rutgersmit** [microsoft/dev-proxy#627]
When you have an application that relies on several API's, and you want to mock more than one API, I'd like to be able to separate the mock responses in a file per API to keep things organised.

I am thinking about the mocksFile accepting an array of filenames.

**Comment by waldekmastykarz** [comment]
Great idea! You can do this already. Check out this sample where we do this for Entra and Microsoft Graph: https://github.com/pnp/proxy-samples/tree/main/samples/microsoft-graph-connector-notification. You can define multiple instances of the MockResponsePlugin each listening to each own set of URLs and tied to a separate mocks file.

**Comment by rutgersmit** [comment]
That's a cool solution! Is there also an option to save the mocked response into a separate file? 
When you've got a lot of mocks, the file becomes quite large. 

Example I was thinking about:
```json
{
    "mocks": [
        {
            "endpoint": "/api/users",
            "method": "GET",
            "responseFile": "users.json"
        },
        {
            "endpoint": "/api/schedules",
            "method": "GET",
            "responseFile": "schedules.json"
        }
    ]
}
```

**Comment by waldekmastykarz** [comment]
Right! So rather than including the response inline, you'd serve it from a separate file. That's neat and would definitely help dealing with large files. Great idea!

**Comment by rutgersmit** [comment]
While starting to implement my own feature request I stumbled upon the fact that... it is already implemented.
If you start the body value with an @ you can specify the file to return. See https://github.com/microsoft/dev-proxy/blob/main/dev-proxy-plugins/Mocks/MockResponsePlugin.cs#L256

This issue can be closed and I won't request any features without thoroughly analysing the code 😬

**Comment by waldekmastykarz** [comment]
All good! The reason why I kept your suggestion open was, that I thought you meant to include the full response in a separate file (eg. status code, headers and body) rather than just the body. But if the body is sufficient for your needs, then we can close this.
