### ISSUE TITLE
Improve install scripts

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#629]
- [ ] Detect PowerShell Constrained Language Mode
- [ ] Improve OS detection
- [ ] Move language mode and OS detection to run first and return remark to use manual install instructions
- [ ] Improve visibility of dot sourcing

Users who use corporate laptops may have [PowerShell Constrained Language Mode](https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/) enabled which will stop the install script from executing correctly and closes the terminal window leaving the users unable to continue. In this scenario, we should detect if the mode is enabled and provide a friendly message to direct users to use the manual install instructions via a short link that targets to https://learn.microsoft.com/microsoft-cloud/dev/dev-proxy/get-started?tabs=manual&pivots=client-operating-system-windows

Error message: `Method invocation is supported only on core types in this language mode`

**Comment by SilentSobs** [comment]
We can have a if statement wrapping our install script ?
```
if (!$ExecutionContext.SessionState.LanguageMode -eq "ConstrainedLanguage") 
```
![image](https://github.com/microsoft/dev-proxy/assets/157403288/e5be03d2-bd0f-4b07-9be2-d907d02bd25c)

**Comment by waldekmastykarz** [comment]
Obsolete in favor of #11
