### ISSUE TITLE
[Microsoft Learn]: Include Dev Proxy content

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#64]
We should consider including some content into the Microsoft Learn documentation so that developers can discover the proxy when looking at our SDKs and learning material.

This will help get the proxy in front of developers early to use when building apps using Microsoft Graph and include it in their development cycles.

We should consider adding high level content and link directly to our Wiki, so that we don't duplicate content and have to maintain in two places.

Some suggestions, there could and most probably be more.

- [Microsoft Graph SDK overview](https://learn.microsoft.com/en-us/graph/sdks/sdks-overview)
- [Explore Microsoft Graph scenarios for JavaScript development](https://learn.microsoft.com/en-gb/training/paths/m365-msgraph-scenarios)

**Comment by waldekmastykarz** [comment]
Great suggestion @garrytrinder! I'll tag it with documentation, even though it's more of content, but it will help us keep it separate from product changes.

**Comment by waldekmastykarz** [comment]
Closing this for now, as we've got our own docs where we point people to.
