### ISSUE TITLE
Update logging so that it includes date and time

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#660]
Change logging formatting so that it includes date and time. It'll help us debug performance-related issues

**Comment by SilentSobs** [comment]
is anyone working on this issue ?

**Comment by waldekmastykarz** [comment]
Not yet, would you like to pick it up?

**Comment by SilentSobs** [comment]
Thanks for the update.  I can pick it up . Also my holiday has started. Do you have any projects that I could take on during this time?

**Comment by waldekmastykarz** [comment]
Cool! What kind of stuff are you interested in? Anything else that you'd like us to do and which isn't on the list?

**Comment by SilentSobs** [comment]
Thank you for considering me. I am proficient in C, C#, Python, IoT, React.js, and .NET, and I easily adapt to other programming languages. I am actively exploring Microsoft products like Azure and am eager to delve deeper into DevProxy. With ample time available, I can dedicate myself fully to any project assigned to me, ensuring not to waste my holiday. Please let me know if there are any projects available, both within and outside the repository. Thank you once again

**Comment by waldekmastykarz** [comment]
We've got several improvements which are documented in the different issues in the repo. Other than that, we've got an exploration opportunity for how we could replace the Titanium Proxy part of Dev Proxy with Yarp. Would you be interested in looking into it?

**Comment by SilentSobs** [comment]
Yes sure . I will try my best to contribute.

**Comment by SilentSobs** [comment]
> We've got several improvements which are documented in the different issues in the repo. Other than that, we've got an exploration opportunity for how we could replace the Titanium Proxy part of Dev Proxy with Yarp. Would you be interested in looking into it?

where I should provide updates on my progress and where discussions regarding the exploration of replacing Titanium Proxy with Yarp should take place?

**Comment by SilentSobs** [comment]
> > We've got several improvements which are documented in the different issues in the repo. Other than that, we've got an exploration opportunity for how we could replace the Titanium Proxy part of Dev Proxy with Yarp. Would you be interested in looking into it?
> 
> where I should provide updates on my progress and where discussions regarding the exploration of replacing Titanium Proxy with Yarp should take place?

...

**Comment by waldekmastykarz** [comment]
> > We've got several improvements which are documented in the different issues in the repo. Other than that, we've got an exploration opportunity for how we could replace the Titanium Proxy part of Dev Proxy with Yarp. Would you be interested in looking into it?
> 
> where I should provide updates on my progress and where discussions regarding the exploration of replacing Titanium Proxy with Yarp should take place?



> > We've got several improvements which are documented in the different issues in the repo. Other than that, we've got an exploration opportunity for how we could replace the Titanium Proxy part of Dev Proxy with Yarp. Would you be interested in looking into it?
> 
> where I should provide updates on my progress and where discussions regarding the exploration of replacing Titanium Proxy with Yarp should take place?

If you're building it on top of the existing Dev Proxy code base, you could open a draft PR so that we can discuss the different changes in context. If you're experimenting on a separate project, we can continue the discussion here: https://github.com/microsoft/dev-proxy/issues/84
