### ISSUE TITLE
[Get started]: Linux install instructions

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#71]
We currently provide install instructions for Windows and macOS in the Get started section.

We should also provide instructions for Linux (Ubuntu).

**Comment by gavinbarron** [comment]
We probably need to ensure that we create separate guidance for WSL vs bare metal Linux too.

**Comment by garrytrinder** [comment]
Good shout @gavinbarron, I'll make a new issue to capture the WSL intructions.

**Comment by waldekmastykarz** [comment]
PR open, pending editorial review
