### ISSUE TITLE
Exclude OpenId permissions from MinimalPermissionsGuidance output

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#816]
![image](https://github.com/microsoft/dev-proxy/assets/11563347/ed43dddd-8726-4a3c-8425-32bed203d178)

When using the `MinimalPermissionsGuidance` plugin to check for excessive permissions, the report contains OpenId permission scopes which are included on the token which are explicitly requested by the app when asking for an access token.

We should consider adding a new configurable property called `permissionsToExclude` to exclude these permissions from the report. The property default should include the default `profile`, `openid` and `email` scopes.

**Comment by waldekmastykarz** [comment]
Great suggestion that'll help decrease false-positives and focus on what matters. Would it be clearer to name the property `permissionsToIgnore` or is `permissionsToExcluded` clearer after all?
