### ISSUE TITLE
Document excluding permissions in MinimalPermissionsGuidancePlugin

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#830]
Changes from #829

**Comment by garrytrinder** [comment]
PR raised https://github.com/MicrosoftDocs/microsoft-cloud-pr/pull/334

**Comment by waldekmastykarz** [comment]
What do you think about releasing it already since we have the feature available in preview?

**Comment by garrytrinder** [comment]
PR merged
