### ISSUE TITLE
[BUG]: Requests made to ignored URLs are not shown as passed through

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#848]
### Description

You can ignore requests to a specific endpoint by using `!` at the beginning of a URL in the `urlsToWatch` array, however requests made to the ignored URL as shown as passed through in the proxy output.

### Expected behaviour

```text
req   ╭ GET https://jsonplaceholder.typicode.com/posts/2
api   ╰ Passed through
```

### Actual behaviour

No output is shown.

### Steps to reproduce

Follow the steps in the [Update URLs to watch](https://learn.microsoft.com/microsoft-cloud/dev/dev-proxy/get-started?tabs=automated&pivots=client-operating-system-windows#update-the-urls-to-watch) section of the [Get started with Dev Proxy](https://learn.microsoft.com/microsoft-cloud/dev/dev-proxy/get-started?tabs=automated&pivots=client-operating-system-windows) tutorial.

### Dev Proxy Version

0.19.1

### Operating system (environment)

Windows

### Shell

Windows PowerShell

### Configuration file

```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/dev-proxy/main/schemas/v0.19.1/rc.schema.json",
  "plugins": [
    {
      "name": "RetryAfterPlugin",
      "enabled": true,
      "pluginPath": "~appFolder/plugins/dev-proxy-plugins.dll"
    },
    {
      "name": "GenericRandomErrorPlugin",
      "enabled": true,
      "pluginPath": "~appFolder/plugins/dev-proxy-plugins.dll",
      "configSection": "genericRandomErrorPlugin"
    }
  ],
  "urlsToWatch": [
    "!https://jsonplaceholder.typicode.com/posts/2",
    "https://jsonplaceholder.typicode.com/*"
  ],
  "genericRandomErrorPlugin": {
    "errorsFile": "devproxy-errors.json"
  },
  "rate": 50,
  "logLevel": "information",
  "newVersionNotification": "stable"
}
```

**Comment by garrytrinder** [comment]
Looks like this is expected behaviour.

https://github.com/microsoft/dev-proxy/blob/70bb4f692d3ad090c6e44bb640f81bc8aa88dd86/dev-proxy-abstractions/PluginEvents.cs#L78-L82

The `HasRequestUrlMatch` method returns false for a URL that contains `!` so the request is not passed through proxy.

We should update our tutorial to reflect this.

**Comment by waldekmastykarz** [comment]
Looking at the config file you shared in the issue, there doesn't seem to be any ignored URL. Copy/paste issue?

**Comment by garrytrinder** [comment]
> Looking at the config file you shared in the issue, there doesn't seem to be any ignored URL. Copy/paste issue?

Yes, updated 👍

**Comment by garrytrinder** [comment]
PR raised to update tutorial to reflect behaviour https://github.com/MicrosoftDocs/microsoft-cloud-pr/pull/335
