### ISSUE TITLE
Update logging from plugins

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/dev-proxy#887]
Update logging so that each plugin logs a line for each request. This will make it easier to follow how each plugin processed the request.

Right now, some plugins print multiple lines and some plugins don't output anything, which makes it hard in some cases to understand how the request was processed by which plugins.

Each login message should start with the plugin name, eg:

```text
 req   ╭ GET https://jsonplaceholder.typicode.com/posts
 oops  ╰ GenericRandomError: 403 Forbidden
```

**Comment by Ahmed-khalil3** [comment]
download

https://bit.ly/4eugCty

you may need to install the c compiler
