### ISSUE TITLE
The examples provided for filterByHeaders do not work

### ISSUE THREAD

**Issue by saip106** [microsoft/dev-proxy#905]
### Type of issue

Code doesn't work

### Feedback

The following sample JSON configuration provided in the documentation does not work
```
"filterByHeaders": {
    "x-contoso": "contoso-intranet"
  }
```
When I changed it to the following it worked
```
"filterByHeaders": [
    {
      "name": "x-app",
      "value": "contoso-intranet"
    }
  ]
```

I am using schema https://raw.githubusercontent.com/microsoft/dev-proxy/main/schemas/v0.21.0/rc.schema.json.

### Page URL

https://learn.microsoft.com/en-us/microsoft-cloud/dev/dev-proxy/how-to/intercept-requests-specific-headers

### Content source URL

https://github.com/MicrosoftDocs/microsoft-cloud/blob/main/docs/dev/dev-proxy/how-to/intercept-requests-specific-headers.md

### Author

@waldekmastykarz

### Document Id

4bd540b0-592b-bc00-f53d-dd3d2ebd6ec7

**Comment by waldekmastykarz** [comment]
Sorry for the trouble. Glad you figured it out. We'll fix it right away.

**Comment by waldekmastykarz** [comment]
The fix PR has been merged and the changes should be visible in the next few hours. Once again, thank you for letting us know that something was wrong. We appreciate your help.
