### ISSUE TITLE
[BUG]: Certificate error (first run)

### ISSUE THREAD

**Issue by hcesar** [microsoft/dev-proxy#912]
### Description

I installed dev-proxy (0.21.0) on MacOS (15.0.1) and when I try to run it for the first time I get the following error:
```
Hosting failed to start
      System.InvalidOperationException: Could not install certificate as it is null or empty.
```

I tried with `--install-cert` but it did work either.

### Expected behaviour

To work

### Actual behaviour

![Image](https://github.com/user-attachments/assets/236be8d7-c9a2-45f9-b87c-9362d11055e3)

### Steps to reproduce

- brew install dev-proxy
- dev-proxy

### Dev Proxy Version

0.21.0

### Operating system (environment)

macOS

### Shell

zsh

### Configuration file

fresh install, no change

**Comment by waldekmastykarz** [comment]
Sorry to hear you're running into trouble and thank you for reporting this to us. Which .NET version do you have installed? I wonder if what you're seeing could be related to https://github.com/microsoft/dev-proxy/issues/886

**Comment by waldekmastykarz** [comment]
Closing due to lack of further response.
