### ISSUE TITLE
feature request: add mock data dynamically

### ISSUE THREAD

**Issue by prakashnathjha** [microsoft/dev-proxy#925]
Is there a way to add the mock data dynamically in the dev proxy server? Right now from what I understand the mock response is static and baked in to the docker image. I am looking to run this as docker container in k8s cluster.

**Comment by waldekmastykarz** [comment]
Could you please explain a bit more what you understand under "add mock data dynamically" and what you'd like to achieve? 🙂

**Comment by prakashnathjha** [comment]
They I want to use dev proxy is as a general purpose mock HTTP server. This gets deployed as a regular kubernetes deployment and in my test environment application uses this mock proxy server instead of making actual API calls. Right now dev proxy has `--mocks-file` cli flag which points to the location of the mock responses per url. 

If I create a docker image I have to bake in the mock response file in to the docker image. Now lets suppose I want to add more mock responses I have to add them in the mock file, rebuild the docker image and deploy it again. Instead of this if there was a way to update the set of mock responses via lets an API call to an already running dev proxy server then this would save a lot of efforts.

Even if the above is not feasible still if we can add support for reading the mock file from lets say S3 that would still be a big help, all I need to do is to restart my dev proxy pods and they get new data from S3.     

What do you feel about it?

**Comment by waldekmastykarz** [comment]
Have you considered mounting a volume with mocks into the Docker image and having Dev Proxy use mocks from that folder? That way you could separate mocks from the image and be able to add/change them without having to rebuild the image each time. Would that work for your scenario?

**Comment by prakashnathjha** [comment]
Yes, that is the approach we are going with right now. We will have an init container that will populate the PV with mock data and then the dev proxy pod will start. Whenever we update the mock data we would need to restart the dev proxy pod.

In case there is any plan to have this kind of support natively in dev proxy in roadmap do let me know. Thanks!

**Comment by waldekmastykarz** [comment]
Are you running the Docker container locally? If so, shouldn't any changes to the files in the volume be reflected automatically without having to restart the container?

**Comment by prakashnathjha** [comment]
Hey @waldekmastykarz , no I am running this on a k8s cluster. Every time we update the mock file we need to restart the pods to read the file again.

On a different topic is it possible to proxy gRPC APIs via dev proxy?

**Comment by waldekmastykarz** [comment]
> Hey [@waldekmastykarz](https://github.com/waldekmastykarz) , no I am running this on a k8s cluster. Every time we update the mock file we need to restart the pods to read the file again.

Understood. Say we supported reading files from a different source, how would Dev Proxy know that the mocks file has changed and it should reload it?

> On a different topic is it possible to proxy gRPC APIs via dev proxy?

We haven't tried it as far as I know. While we might theoretically be able to intercept requests, if I understand it correctly, we won't be able to examine them because they're binary and we've got no understanding of their shape.

**Comment by prakashnathjha** [comment]
> Understood. Say we supported reading files from a different source, how would Dev Proxy know that the mocks file has changed and it should reload it?
Reloading can be done on demand basis. Once new data is uploaded one can restart the deployment. Or maybe one can restart a deployment at some regular interval with Pod Disruption Budget to ensure at least there is one pod running. 

On the gRPC front you are right, Dev Proxy will have no idea about the shape of the object. Plus since gRPC operates with HTTP 2 I am not sure if that can also cause some problems? In case you are able to perform mocking with gRPC please do share steps for that.

**Comment by waldekmastykarz** [comment]
> Reloading can be done on demand basis. Once new data is uploaded one can restart the deployment. Or maybe one can restart a deployment at some regular interval with Pod Disruption Budget to ensure at least there is one pod running.

How would that be different from what you're doing now?

_Every time we update the mock file we need to restart the pods to read the file again._

**Comment by prakashnathjha** [comment]
> How would that be different from what you're doing now?

If Dev Proxy pull mock data from S3 (or some other source) then I don't need to use persistent volume, plus I don't need to have an init container that runs before Dev Proxy container to pull mock data into PV.

**Comment by waldekmastykarz** [comment]
Understood, so you'd only need to restart Proxy so that it can load the latest mocks file.

Have you considered solving it outside of Proxy for example by using curl to download the file when the container starts and before you launch Proxy? If this works it would be the easiest way to go about it because it solves the problem without any Proxy-specific work, which means that you can integrate it with any service/location.

If that's not possible, another solution could be building a separate Proxy plugin that downloads a file and puts it in the right place on disk. We'd need to verify if that's still on time for Proxy to pick it up.

**Comment by waldekmastykarz** [comment]
Closing due to lack of further response
