### ISSUE TITLE
Add support for generating OpenAPI specifications using OpenAPI v2

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#952]
The `OpenApiSpecGeneratorPlugin` is currently fixed to generate a spec using v3 of the OpenAPI standard.

Power Platform makers can use OpenAPI specifications to create custom connectors, however the Power Platform only supports OpenAPI specifications that use v2. Custom connectors play a big role in connecting workflows to external systems in Power Automate, Power Apps and agents built using Copilot Studio.

We should update the plugin with a new configuration option to override the default version used during generation of the specification. The option will only accept `2` or `3` as a valid value, and will default to `3`, if the property is not provided to ensure current behaviour.

Example:

```json
{
  "openApiSpecGeneratorPlugin": {
    "specVersion": 2,
    "includeOptionsRequests": false
  }
}
```

EDIT: Suggestion from Daniel Laskewitz ❤️

**Comment by waldekmastykarz** [comment]
Great idea! Let's make it more widely usable.

Do we need `specVersion` or would just `version` be enough?

**Comment by garrytrinder** [comment]
`version` feels too vague IMO. Is it the version of the plugin or the spec?

**Comment by waldekmastykarz** [comment]
> `version` feels too vague IMO. Is it the version of the plugin or the spec?

We don't version plugins that way but I get your point. Let's roll with `specVersion`.
