### ISSUE TITLE
[Feature] Print timestamp for each intercepted request

### ISSUE THREAD

**Issue by gehho** [microsoft/dev-proxy#953]
It would be nice to have the timestamp printed on the console for each intercepted request. This would make it easier to associate requests with log output from our application. Furthermore, if you run multiple tests in a row without restarting DevProxy, it is sometimes hard to identify where the next test run started in the console.

Something like this would be nice:

```
 req   ╭ GET https://contoso.com/some/request/
 time  | 2024-12-05 17:25:12.345
 oops  │ LatencyPlugin: Delaying request for 7000ms
 api   ╰ Passed through
```

**Comment by waldekmastykarz** [comment]
Thank you for the suggestion @gehho! This makes perfect sense. We should definitely allow showing timestamp

**Comment by garrytrinder** [comment]
Thanks for the suggestion @gehho 

We just released this functionality in the latest beta release.
