### ISSUE TITLE
Add support for generating OpenAPI spec in YAML

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/dev-proxy#956]
We currently only support JSON as the format when generating an OpenAPI spec from intercepted requests and responses. We should add support for developers to choose YAML which is a valid format for an OpenAPI spec and is typically the preferred format.

> Basically, JSON does not support comments and requires: commas separating fields, curly brackets around objects, double quotation marks around strings and square brackets around arrays. On the other hand, YAML requires hyphens before array items and relies heavily on indentation, which can be cumbersome on large files (indentation is entirely optional in JSON).
> 
> YAML is typically preferred because of its slightly reduced file size, but the two formats are completely interchangeable (as long as [YAML 1.2](https://en.wikipedia.org/wiki/YAML#Comparison_with_JSON) is used). All examples in these pages will be given in YAML.
> 
> Source: https://learn.openapis.org/specification/structure.html

**Comment by waldekmastykarz** [comment]
Good idea! Let's do this!
